
# ----------------------
# Git Aliases
# ----------------------
alias ga='git add'
alias gaa='git add .'
alias gaaa='git add --all'
alias gau='git add --update'
alias gb='git branch'
alias gbd='git branch --delete '
alias gc='git commit'
alias gcam='git commit --amend --no-edit'
alias gcm='git commit --message'
alias gcf='git commit --fixup'
alias gcnm='git commit --no-verify -m'
alias gcan='git commit --amend --no-edit --no-verify'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcom='git checkout master'
alias gcos='git checkout staging'
alias gcod='git checkout develop'
alias gd='git diff'
alias gda='git diff HEAD'
alias gfom='git fetch origin master'
alias gi='git init'
alias gpl='git pull'
alias gl='git log'
alias glg='git log --graph --oneline --decorate --all'
alias gld='git log --pretty=format:"%h %ad %s" --date=short --all'
alias gm='git merge --no-ff'
alias gma='git merge --abort'
alias gmc='git merge --continue'
alias gp='git push'
alias gpo='git push origin'
alias grb='git rebase'
alias grbi='git rebase -i'
alias grbon='git rebase-onto'
# git rebase-onto master(main) feature-b-off-a feature-a
alias grt='git restore'
alias grts='git restore --staged'
alias gs='git status'
alias gss='git status --short'
alias gst='git stash'
alias gsta='git stash apply'
alias gstd='git stash drop'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gsts='git stash save'
alias gunc='git uncommit'
alias gitignore='git update-index --assume-unchanged'
alias gitignored='git ls-files -v | grep -e "^[hsmrck]"'
alias gitunignore='git update-index --no-assume-unchanged'

